name: Close Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v2
        with:
          comment: "We do not accept PRs on this repository. Please read https://async-aws.com/contribute/website.html and then make a PR to https://github.com/async-aws/aws"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
